### ISSUE TITLE
Web extension for adding new puzzles

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#209]
During last year's MITMH, we added puzzles to the smallboard database manually via the website. I think it would reduce interruptions to users' solving puzzles if we provided a chrome/firefox extension that did this from a newly opened puzzle webpage.

Example user flow:

- :calendar: Before the hunt, team organizers encourage teammates to install the web extension and authenticate it with smallboard
- :tada: During the hunt, User unlocks a new puzzle on the MITMH website
- :computer_mouse: User clicks the extension icon in their browser, sending the current page's `<title>` data and URL to smallboard via REST API to create a new puzzle in the db
- :jigsaw: User continues to explore the new puzzle, without ever having to leave the MITMH puzzle webpage

This feature would likely involve exposing smallboard's puzzle instance creation via a REST API for the extension to call.

**Comment by erwa** [comment]
Ooh, this would be helpful! And seems like a fun thing to implement :D.

I think the extension could also query to see if an entry already exists for the current puzzle, and provide direct links to the sheet and Discord for the puzzle without the user having to return to Small Board.

**Comment by akirabaruah** [comment]
Yeah! I was thinking quick links would be cool too! :grinning:

**Comment by akirabaruah** [comment]
FYI, I've started prototyping this - I might have some questions during today's sync

**Comment by akirabaruah** [comment]
@erwa if you wanted to collaborate on it, lemme know :smile:

**Comment by erwa** [comment]
> @erwa if you wanted to collaborate on it, lemme know 😄

Go for it. I won't have time to do any dev for a couple weeks as I'm finishing up my semester.

**Comment by akirabaruah** [comment]
Okay 👍 good luck on exams(?) and papers(?) and stuff!

**Comment by maximized** [comment]
I sorta have this working. I need to clean up the permissions today. My goal is to have this working and sharable for testing before tomorrow

The screencast below just shows off that you can go to a separate page, click on the extension, and then a puzzle will appear in Cardboard. The details of the entry are still a WIP. 
https://watch.screencastify.com/v/Fxe2gYvZ6FmdWfz60hHT
