### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#215]
Let the user toggle between light/dark themes in the smallboard site (for those late-night solve sessions 🌙 )

Possibly use the browser's `prefers-color-scheme` field to automatically switch depending on the user's browser prefs: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by akirabaruah** [comment]
@rawxfish seemed like you were interested?

**Comment by rawxfish** [comment]
Sure, I can do this

**Comment by bcai2** [comment]
A guide to dark mode and Bootstrap 4 that might be useful: https://github.com/vinorodrigues/bootstrap-dark
