### ISSUE TITLE
Puzzle channel categories in Discord

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#224]
Bot should organize its generated puzzle-specific channels into categories like "archive", "backsolved", "low-prio", "obsolete"

**Comment by asdfryan** [comment]
Marked this as critical since we will otherwise run into scalability limits (50 channels allowed per category). I plan to work on this Friday/Saturday.

**Comment by asdfryan** [comment]
Fixed the scalability issue -- though it's perhaps worth thinking more about further categorization.

**Comment by rawxfish** [comment]
As discussed in Discord, we are going to create categories for each meta. For puzzles that go to multiple metas, we start with a simple heuristic to choose which one it should be assigned to and change as needed manually.

**Comment by rawxfish** [comment]
Going to close this issue since we already have ARCHIVE and PUZZLES categories. Doing meta categories tracked in #468
