### ISSUE TITLE
Run black formatter in makemigrations

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#232]
It would be nice if `./manage.py makemigrations` automatically applied `black` formatting to the generated migration files.

Right now, the developer flow is to run `./manage.py makemigrations` and then run `black` on the generated files (perhaps via `pre-commit run --all-files`). That's two steps instead of one :sweat_smile:

**Comment by akirabaruah** [comment]
@rgossiaux from our discussion

**Comment by cs-miller** [comment]
gonna suggest we create a pyproject.toml to configure black, among other things

**Comment by rgossiaux** [comment]
I think setting up pre-commit removes the need for this since it'll format your migrations when you commit them.
