### ISSUE TITLE
Better test coverage for hunts app

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#239]
Based on our coverage stats in https://codecov.io/gh/cardinalitypuzzles/smallboard, the `hunts/views.py` module could use some tests.

**Comment by akirabaruah** [comment]
@ramansrivastava can you look into adding tests for the functionality in `hunts/views.py`?

First, since you mentioned you're new to django, I'd recommend skimming through the [django tutorial here](https://docs.djangoproject.com/en/3.1/#django-documentation) and [especially focus on this section on testing views](https://docs.djangoproject.com/en/3.1/intro/tutorial05/#testing-our-new-view).

Once you have a better idea of how django and django testing works, try running the tests for our project by following the [dev-guide](https://github.com/cardinalitypuzzles/smallboard/blob/master/dev-guide.md#running-tests).

Then, take a look at `hunts/views.py` to get an idea of how some of it works and see if you can add a new test in `hunts/tests.py`.

**Comment by ramansrivastava** [comment]
@akirabaruah got it ,but i still dont understand it completely is their any way you can explain it more deeply maybe on discord or any other platform, if not possible then its ok i will try to figure it out myself.

**Comment by ramansrivastava** [comment]
> @ramansrivastava can you look into adding tests for the functionality in `hunts/views.py`?
> 
> First, since you mentioned you're new to django, I'd recommend skimming through the [django tutorial here](https://docs.djangoproject.com/en/3.1/#django-documentation) and [especially focus on this section on testing views](https://docs.djangoproject.com/en/3.1/intro/tutorial05/#testing-our-new-view).
> 
> Once you have a better idea of how django and django testing works, try running the tests for our project by following the [dev-guide](https://github.com/cardinalitypuzzles/smallboard/blob/master/dev-guide.md#running-tests).
> 
> Then, take a look at `hunts/views.py` to get an idea of how some of it works and see if you can add a new test in `hunts/tests.py`.

ok

**Comment by akirabaruah** [comment]
Yeah I'd be happy to chat on Discord, but I'm actually about to go to bed for today :sweat_smile: so it might have to be in 8 hours or so

For now, if you could maybe run through the django tutorial to get a better understanding of the basics and maybe check out the code, that would be great - thanks!

**Comment by ramansrivastava** [comment]
> Yeah I'd be happy to chat on Discord, but I'm actually about to go to bed for today 😅 so it might have to be in 8 hours or so
> 
> For now, if you could maybe run through the django tutorial to get a better understanding of the basics and maybe set up your local development environment, that would be great - thanks!

no worries thx.

**Comment by akirabaruah** [comment]
@ramansrivastava I may not be as quick to respond until 6pm Pacific Time, but feel free to ask questions here: https://discord.gg/PNQSQWuyuS

**Comment by ramansrivastava** [comment]
sure

**Comment by ramansrivastava** [comment]
> @ramansrivastava I may not be as quick to respond until 6pm Pacific Time, but feel free to ask questions here: https://discord.gg/PNQSQWuyuS

just want to let you know these days i am kinda busy with life ,so it might take some time to add test.

**Comment by akirabaruah** [comment]
okay thanks for the heads up. do you have a rough idea of when you'd be
able to work on those tests again?

**Comment by ramansrivastava** [comment]
probably after 18, if its ok?

**Comment by akirabaruah** [comment]
Ah after 12/18 should be fine. Just as an FYI, we made add some test coverage between now and then, but probably not 100%, so your help would be gladly appreciated.

Have you already joined the discord I linked above? Happy to chat there if it's faster.

**Comment by ramansrivastava** [comment]
> Ah after 12/18 should be fine. Just as an FYI, we made add some test coverage between now and then, but probably not 100%, so your help would be gladly appreciated.
> 
> Have you already joined the discord I linked above? Happy to chat there if it's faster.

yes i have joined the discord server ,right now i am getting familiar with django so will text you there for help when start working which will be after 18.

**Comment by rawxfish** [comment]
Test coverage of hunts app is at ~91%, which is above average compared to the rest of the codebase. The testing gaps are now in chat, google API library, and the puzzles app
