### ISSUE TITLE
Pipenv installation docs are incomplete

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#248]
Our dev guide currently describes [installing pipenv](https://github.com/cardinalitypuzzles/smallboard/blob/master/dev-guide.md#setting-up-a-python-environment) on ubuntu as `sudo apt install pipenv` but this [doesn't seem to work](https://github.com/pypa/pipenv/issues/4343) out of the box.

We should probably just link to the official [pipenv installation docs](https://pipenv.pypa.io/en/stable/#install-pipenv-today).

**Comment by akirabaruah** [comment]
@cs-miller @pcvera

**Comment by cs-miller** [comment]
did you actually encounter this error? this works totally fine for me on Ubuntu 20.04

![Screenshot 2020-12-06 143810](https://user-images.githubusercontent.com/18579508/101290496-b4bde080-37d0-11eb-9c8b-804871083bcb.png)

**Comment by cs-miller** [comment]
also it already does link to those docs btw. i can just remove the suggested shell command.

**Comment by akirabaruah** [comment]
I think @pcvera was running into the problem on ubuntu on WSL.

But yeah, since we already have the link to the official docs, we can probably remove the ubuntu command?

In general, we should probably just wrap all of this one-time setup stuff into a single idempotent command that folks can run (as we've discussed in the past) to simplify things.

**Comment by akirabaruah** [comment]
Filed #249 for the single command dev setup workflow

**Comment by cs-miller** [comment]
I don't see a simple way of installing all the "pre-reqs" in one command if you can't make any assumptions about the environment and the only thing guaranteed to be installed is git. Or rather that command is docker-compose, right? I feel it's reasonable to say "this works on Ubuntu LTS, for other environments see links", but going link-only is definitely simpler.

**Comment by rawxfish** [comment]
Going to close this since we have switched to poetry in #533
