### ISSUE TITLE
Shouldn't be able to change the color of a meta tag

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#268]
Right now (in both the old UI and the new React UI) you can change the color of a meta tag by trying to create a new tag with the same name. If the meta is called "Meta", you can create a tag with the name "Meta" and some other color like blue, and it'll change the meta tag's color.

**Comment by victorchan314** [comment]
Will change the behavior to prevent creation of a tag that already exists.

**Comment by rgossiaux** [comment]
Or maybe just prevent changing the color? So if the tag exists, then just
use its existing color

**Comment by victorchan314** [comment]
From a UI perspective it doesn't really make sense to allow creation of an existing tag and silently merge it with the existing tag. Unless you want to allow duplicate tags with multiple colors and keep a separate tag ID for each one, which might be confusing. Thoughts?

**Comment by rgossiaux** [comment]
Nah, we enforce unique names per tag & I don't think we should change that. I think I was thinking that you might be trying to create a tag for something without noticing that the tag already existed and then applying that existing tag could be friendlier. But you're right that that sounds like it could be confusing so I'm cool with whatever you want to do.

**Comment by victorchan314** [comment]
Just kidding, I didn't realize that creating a new tag and adding a tag to a puzzle use the same API. It's not possible to distinguish between the two operations without separating them into different APIs, so I'm just going to implement the silent behavior. Aka creating a tag that exists will change the color of the tag if it is not a meta tag.
