### ISSUE TITLE
De-clutter React UI

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/cardboard#280]
Context: https://github.com/cardinalitypuzzles/smallboard/pull/275#discussion_r549605998

![smallboard-ui](https://user-images.githubusercontent.com/1498449/103448160-5b6b9480-4c4a-11eb-94fa-266dc8f28b33.png)

We've got a lot of buttons on our UI for editing/adding/deleting puzzles and answers. We can de-clutter this by removing these buttons and exposing these functionalities not on the table itself, but on the modal dialog instead.

**Comment by erwa** [comment]
Note the screenshot above is out-of-date; the Tags and Meta columns have been combined into one now. There's also a "Chat" column that has a link to the Discord text channel for the puzzle.

**Comment by rgossiaux** [comment]
We've streamlined this enough that I'm just going to close this issue
