### ISSUE TITLE
Integrate Discord tags/roles with smallboard tags

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#303]
Maybe this is already tracked somewhere but we have a bunch of roles for people interested in certain types of puzzles on discord--we should integrate those with smallboard tags so when that tag is added to a puzzle we @-mention the people with the role (as part of this we should also make sure that we have default tags that correspond to all those roles)

**Comment by asdfryan** [comment]
@rgossiaux -- what do you think of adding `ChatRole`s at initialization time for the DiscordClient (which is a singleton)? Discord API supports getting all roles from a guild I think.

We can skip things like `devs`, `admin`, and `everyone`.

**Comment by rgossiaux** [comment]
Hmm yeah, feels like there are pros and cons. I like the idea of making this way easier to set up though.

Maybe we can revisit after the hunt? Longer-term I feel like we should have some hunt config pages/models for handling all this stuff (discord servers/channels/roles, Drive folder(s), permissions/users and so on). Then maybe we can expose some way in that UI to query the Discord API to automatically grab the roles & make it easy to config. What do you think?

**Comment by rgossiaux** [comment]
I think #671 tracks improving the initialization of this stuff, so closing this one back again.
