### ISSUE TITLE
greenlet.greenlet size warnings

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#320]
I get tons of warnings when I start the docker container that look like this:

```<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject```

Doesn't seem to cause any issues but it's pretty spammy. Think it's related to discord or to gevent.

**Comment by asdfryan** [comment]
Unfortunately, `disco.py` requires `gevent` to be <2 and >=1.3.0.

However, according to [this](https://github.com/gevent/gevent/issues/1260#issuecomment-697346787), gevent 20.9.0 is required to use (a standard build of) greenlet 0.4.17.

**Comment by asdfryan** [comment]
The warnings go away if you add `greenlet = "<0.4.17"` to `Pipfile`.

Not sure it's actually a good idea to do this though.

**Comment by rgossiaux** [comment]
We removed disco.py (see #515) so this is fixed
