### ISSUE TITLE
First of multiple answers for a puzzle marks status as SOLVED

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#346]
Submitting a single answer marks a puzzle as SOLVED, which should be fine for the majority of cases. However, for puzzles with multiple answers, we should be able to leave the status at SOLVING, STUCK, EXTRACTION, etc.

Simple solution here is to make puzzle status editable even after switching to the SOLVED state.

**Comment by rgossiaux** [comment]
I think this is done.
