### ISSUE TITLE
Change puzzle uniqueness to include both the title and the URL

### ISSUE THREAD

**Issue by maximized** [cardinalitypuzzles/cardboard#398]
Right now, if you make a puzzle with the same URL as a previous puzzle, we get an error from the DB. In case Galactic does something crazy that requires us solve a puzzle on the exact same page again, we want to be able to create a separate Smallboard entry for the later versions.

**Comment by rgossiaux** [comment]
I wonder if the potential benefits of relaxing this are worth the drawbacks of getting duplicate puzzles. What do you think? If need be we could always add blank anchors or query parameters to the puzzle url to get around the uniqueness check right now.

**Comment by asdfryan** [comment]
Per our discussion offline, there are workarounds (adding # to the end of URLs, etc)
