### ISSUE TITLE
Improve hunt start_time/end_time UI

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/cardboard#406]

**Comment by bcai2** [comment]
There are several nice React widgets, but this would likely involve rewriting the hunt creation page in React.

https://blog.bitsrc.io/13-react-time-and-date-pickers-for-2020-d52d88d1ca0b

**Comment by rgossiaux** [comment]
I think we should just switch to the native HTML controls:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

I think a custom datepicker is overkill for just this one minor piece of UI.
