### ISSUE TITLE
Standardize spelling of Small Board

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/cardboard#418]
Currently, smallboard.app uses "Smallboard" in the top left but our GitHub README.md uses "Small Board". We should decide on a spelling and stick to it. (This can wait until after the MITMH 2021)

**Comment by rgossiaux** [comment]
Or "smallboard" (lowercase letters because it's small). Which of the three do people like the most?

**Comment by maximized** [comment]
Oooo, I like smallboard.


Max Chang

**Comment by rgossiaux** [comment]
Obsolete after the Cardboard renaming.
