### ISSUE TITLE
Search for puzzle by name

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#441]
Need a command like `!find foo` or something to get you the channels for a puzzle. Too hard to jump around right now.

**Comment by akirabaruah** [comment]
Assuming this is a bot command, yeah?

**Comment by rgossiaux** [comment]
Yeah. But actually once I learned about cmd+k this wasn't as much of an issue for me personally

**Comment by rgossiaux** [comment]
I think cmd-k solves this issue.
