### ISSUE TITLE
Change name to cardboard

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#507]
Discussed in the Discord channel (it's a pun on Cardinality).

**Comment by rawxfish** [comment]
I renamed the repo from smallboard => cardboard. We need to decide on a new domain: https://porkbun.com/checkout/search?q=cardboard&all=1

**Comment by erwa** [comment]
What do we need the new domain for? When we use cardboard, we can just host it on Heroku, right (e.g.: cardboard-mitmh22.herokuapp.com)?

**Comment by rawxfish** [comment]
We don't need it per se, but we did have smallboard.app last year.

**Comment by rawxfish** [comment]
cardboard.herokuapp.com was taken so I used cardinality-cardboard.herokuapp.com. Can switch it to cardboard-mitmh22 if we decide we can't fix #191 in time.
