### ISSUE TITLE
Better error handling for Google API

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#561]
Apparently if you share the Drive folder with everybody, the response [here](https://github.com/cardinalitypuzzles/cardboard/blob/4f448f01347f48674e48264712da8ef7d405b9a1/google_api_lib/sync_tasks.py#L35) may not include any email addresses. We should handle that. More generally we should try to generate good error messages for these API calls if we can.

**Comment by erwa** [comment]
Here's what the error you encounter might look like:

![image](https://user-images.githubusercontent.com/544734/149048992-1821fec5-aa73-47b6-9e27-76bd9d9b4dad.png)
