### ISSUE TITLE
When garbage collecting old Discord channels, remove the voice channel even if the text channel still exists

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#591]
Looks like if the text channel gets kept (because it contains text), then the voice channel also is kept. In this case we could keep the text channels and delete the voice channels.

**Comment by rawxfish** [comment]
The code's behavior is already like that from what I can tell. The only thing I can think of is the code bugs out when it tries to figure out if the text channel should be kept and the celery task never gets to the lines of code that cleans up voice. 

Switched the order of the cleanups so audio happens before all the stuff happens for text in #668, which will hopefully resolve this issue.
