### ISSUE TITLE
Should include feeders on metameta, etc sheets instead of just meta sheets

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#595]

**Comment by erwa** [comment]
Would have been useful for The Ministry meta this year: https://www.bookspace.world/puzzle/the-ministry/

**Comment by rgossiaux** [comment]
Lol I actually was thinking of the endgame puzzle when I filed this as well: https://www.bookspace.world/puzzle/completing-the-story/solution/

I think we can maybe separate the feeder answers from the meta ones in the sheet with some blank rows (in case it's a metameta where the feeder answers are not useful, so that you can copy/paste only the meta answers)
