### ISSUE TITLE
Expand row icon looks very out of place on Windows

### ISSUE THREAD

**Issue by pcvera** [cardinalitypuzzles/cardboard#597]
I mean look at it

![image](https://user-images.githubusercontent.com/1635030/149721571-687fffc1-0433-444e-a424-692addf109f4.png)

**Comment by erwa** [comment]
Hmm, seems like some fallback font issue. I see it also on my PC, but if I delete "Segoe UI Emoji" from the font-family list, it goes back to "normal" (looks more like the downward-pointing triangle below it)

![image](https://user-images.githubusercontent.com/544734/149857212-ebb60510-809d-4011-bd2d-9f075a1cb41f.png)

**Comment by erwa** [comment]
This is what the right-pointing triangle looks like after deleting the Segoe UI Emoji font from the font-family. Looks more normal:
![image](https://user-images.githubusercontent.com/544734/149877935-009edef9-c083-43e8-a3fd-fef2b72aa275.png)

**Comment by erwa** [comment]
Segoe UI Emoji looks like some default font that comes with Windows 10+: https://docs.microsoft.com/en-us/typography/font-list/segoe-ui-emoji

We can probably specify some font overrides so a more consistent-looking font is used for the triangles.
