### ISSUE TITLE
transfer ownership now requires consent

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/cardboard#616]
```ERROR: Consent is required to transfer ownership of a file to another user.```

Google Cloud has made it so that when transferring file ownership between users who are not part of the same organization, the transfer requires the new owner to accept the invitation.

Since this requires the new owner to accept the invitation, the transfer cannot be done programmatically via API, so this method fails for users who don't belong to the same organization.

We need the ownership transfer to make scripts work.

**Comment by rawxfish** [comment]
A work around is to pre-make ~200 sheets before the hunt and make sure ownership is properly transferred. This just adds an additional click per sheet to MITMH 2022, when we had to pre-make the sheets to get the formulas to work.
