### ISSUE TITLE
Rewrite discord integration + make channel creation optional

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#622]
This could be configured through hunt settings or something.

**Comment by asdfryan** [comment]
Maybe we can have a checkbox on the creation form (default can be configured at the hunt settings level). Should be pretty easy to implement.

**Comment by rawxfish** [comment]
In addition to checkbox on creation form, maybe the links on the tables to the discord channel should be "create a channel" links if channel does not exist. So that if a puzzle gets worked on by remote people after it's creation in cardboard, people can still make channels.

**Comment by asdfryan** [comment]
> In addition to checkbox on creation form, maybe the links on the tables to the discord channel should be "create a channel" links if channel does not exist. So that if a puzzle gets worked on by remote people after it's creation in cardboard, people can still make channels.

I was planning to make it so that the edit modal has the checkbox available
