### ISSUE TITLE
Deprecate GOOGLE_DRIVE_HUNT_FOLDER_ID completely

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#662]
We still use GOOGLE_DRIVE_HUNT_FOLDER_ID for getting list of allowed emails for OAuth, but this is simultaneously a field in HuntSettings for everything else.

**Comment by rohit-rao** [comment]
How do the ACLs work when multiple hunts are configured? Do the individual hunt folders control access to each hunt, or is there only one global ACL?

Would you take a CL to move the global ACL to a new settings variable, like `GOOGLE_DRIVE_ACL_FOLDER_ID`? This wouldn't change any underlying behavior, but would make it clearer that you definitely need to set this variable.
