### ISSUE TITLE
Consider exposing some kind of "last edited" info

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#674]
We could possibly use the activity data we're pulling from google drive to determine the last time that a puzzle had sheets activity and display that somewhere (?). Need to make sure this data is more useful than noisy though.

**Comment by pcvera** [comment]
would be cool to drop location tags after a certain amount of inactive time so puzzles that aren't actually happening anywhere don't have misleading tags

**Comment by rawxfish** [comment]
> would be cool to drop location tags after a certain amount of inactive time so puzzles that aren't actually happening anywhere don't have misleading tags

Tracked in #678
