### ISSUE TITLE
Search bar not giving full results

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/cardboard#677]
If you go to the 2023 mystery hunt and search "museum ru" you don't get the puzzle Museum Rules. Only if you add the L at the end does it appear.

**Comment by npinsker** [comment]
I can't reproduce this (1/23/24), seems to be WAI?

**Comment by rgossiaux** [comment]
I suspect that I saw this because it was collapsed under its parent (`The Cafe (Atrium)`); the L is needed to filter that one out.

Think we can just close this one and use that issue to track the general UX problems with the search results display
