### ISSUE TITLE
Missing scroll on tag modal

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#681]
Cannot scroll on the add tag modal once the tags list got too long. Solved by zooming out, but still unpleasant:
![image](https://user-images.githubusercontent.com/1312469/213964680-2c47d8b9-add1-406c-a398-ede99420c51b.png)

**Comment by akirabaruah** [comment]
From dev chat today: Might be worth redesigning this tag editing UI to be less cluttered.
