### ISSUE TITLE
Add stats on normal vs back solved vs freebied

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#703]

**Comment by maximized** [comment]
<img width="287" alt="image" src="https://github.com/cardinalitypuzzles/cardboard/assets/4155621/15267518-9c8a-4aa7-837c-05f90e3fa4b0">

@rawxfish is this what you were thinking of or are you looking for another line on the plot or another set of numbers on the page itself?

**Comment by rawxfish** [comment]
This seems fine to me

**Comment by rgossiaux** [comment]
It would be cool if there were some checkboxes to toggle for the graph like "Include backsolves", "Include free answers" but not sure how complicated that is to add

**Comment by maximized** [comment]
I think the checkboxes and toggling would be fairly doable. With only a few toggles, we can compute each slice and subtract those that are toggled off from the sum. 

I don't know if I would see myself using this feature.
