### ISSUE TITLE
Can't join hunt using my email address 

### ISSUE THREAD

**Issue by julielamberth** [cardinalitypuzzles/cardboard#731]
I can't join cardboard.  My email address is julielamberth@mac.com and I've confirmed my team has the right email for me, but get an error. Can't paste it all because of length but here's the first part.  Happy to email the rest to someone.
<h1 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration: none; padding: 0px; margin: 0px; font-weight: normal;">AuthForbidden at /complete/google-oauth2/</h1><pre class="exception_value" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration: none; padding: 0px; margin-top: 10px; margin-bottom: 10px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87);">Your credentials aren't allowed</pre>
Request Method: | GET
-- | --
https://amateurhour-cardboard-68fa133dd61c.herokuapp.com/complete/google-oauth2/?state=pyfa8tUPqCWtXAonaqSRLHBoKK2RnJe5&code=4%2F0AfJohXk22MA9eTfpi2BIegqcKQjFDBP7e20YNDkxcxRJx8IoJA3Mgif5js9gKRqYikG5aQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none
4.1.10
AuthForbidden
Your credentials aren't allowed
/app/google_api_lib/sync_tasks.py, line 33, in auth_allowed
social_django.views.complete
/app/.heroku/python/bin/python
3.11.5
['/app',  '/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python311.zip',  '/app/.heroku/python/lib/python3.11',  '/app/.heroku/python/lib/python3.11/lib-dynload',  '/app/.heroku/python/lib/python3.11/site-packages']
Fri, 05 Jan 2024 09:29:42 -0500

**Comment by maximized** [comment]
Hi Julie. Thank you for reaching out. From your error message, I take it that you are on Amateur Hour. This specific repository is Cardinality's version of Cardboard. I suspect that your team has forked our repository (which is perfectly fine) and brought up their own instance of Cardboard (possibly with some customizations). I recommend contacting your development team to help you debug.
