### ISSUE TITLE
Clean up error message when Puzzle title is too long

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#741]
Right now, users might see this:

![image](https://github.com/cardinalitypuzzles/cardboard/assets/6751517/98a00a4f-072f-4b56-95f9-922c67e43ed0)

We should probably at least extract the error and avoid printing raw JSON.

**Comment by rgossiaux** [comment]
Duplicate of #294 

We should certainly get around to fixing this at some point though
