### ISSUE TITLE
Copy list of all puzzle answers into Sheets

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#793]
Need a simple way to copy all puzzle answers from Cardboard into Sheets for solving Metas, etc.

**Comment by erwa** [comment]
I thought when a puzzle is added under a meta, the first tab of the meta sheet auto-refreshes with all the answers of the puzzles for the meta. But it's been a while since I've used Cardboard so maybe something changed...

**Comment by erwa** [comment]
I think I found the code - in a few places, when something is updated and we might want to update the meta feeder answers, we call `update_meta_and_metameta_sheets_delayed`.

![image](https://github.com/user-attachments/assets/7aba5232-1410-448b-8c37-16a0012c655c)

**Comment by rgossiaux** [comment]
Yeah I think this already works? Every meta sheet has a tab in it with its feeder puzzles & answers.

**Comment by maximized** [comment]
The situation here is an unassigned meta round. The current workaround would be to assign all of those puzzles to a common "round" meta, remove answers from that "round" as they get used, and then copy and paste the remaining answers fro the common "round" meta's sheet to the individual meta sheets as they get assigned. 

Not sure if there is a strictly better UX but that was the use case we had in mind here.

**Comment by erwa** [comment]
Ah, I see, thanks for clarifying @maximized. Yeah, I guess copying the answers from the "round" meta answers sheet to individual meta sheets would probably be the easiest way for now.

**Comment by rgossiaux** [comment]
I think once you learn which meta certain puzzles belong to you can move the feeders to that meta in cardboard and the individual meta will have those answers. But idk the details of this round & this does sound kind of janky. I don't think cardboard handles these situations without clear meta structures amazingly well, there are a couple issues 
 #598 and #494
