### ISSUE TITLE
Poetry buildpack no longer needed?

### ISSUE THREAD

**Issue by calvinballing** [cardinalitypuzzles/cardboard#818]
I'm trying to follow the steps to set up cardboard for the first time.  I have not used it before.

I've consistently been having the build die on me here:
```
remote: -----> Add Poetry to the PATH
remote: -----> Force usage of active Python and disable creation of virtualenvs
remote: -----> Export requirements.txt from Poetry
remote: /bin/sh: 1: python: not found
remote:
remote: Command python -c "import sys; print(sys.executable)" errored with the following return code 127, and output:
remote:
remote:  !     Push rejected, failed to compile Python Poetry app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
```

After some investigation, I found that the poetry buildpack from which cardinality's poetry buildpack was cloned been [updated with a deprecation notice](https://github.com/moneymeets/python-poetry-buildpack?tab=readme-ov-file#python-poetry-buildpack), due to the [recent inclusion of poetry in the main heroku/python buildpack](https://github.com/heroku/heroku-buildpack-python/pull/1682) (as of Nov. 6, 2024).

After removing the poetry buildpack, I was able to get the build to complete.  I had to make another adjustments to complete build and deploy (`heroku config:set DEBUG=false`, because silk was not being found). 

I don't know if I've actually fixed the issue with this one change, since I haven't looked into why silk is not being found, and whether cardinality customized the poetry buildpack in any ways that need to still be replicated.

Anyway, I think the docs should probably be updated to reflect this change, and possibly there are some knock-on effects that this might require.

**Comment by rawxfish** [comment]
Ah sorry about that. With the old buildpack, we also had `DISABLE_POETRY_CREATE_RUNTIME_FILE=1` and `POETRY_VERSION=1.3.1`, we didn't customize it beyond that. I tested deploying without and confirmed that it works with just the new heroku/python buildpack.

I'm surprised that you needed to explicitly set `DEBUG`, the default value should be false if it is not set, which disables silk. One of our instances is running without a `DEBUG` set and I'm not able to reproduce, possibly it only happens with new Heroku apps or something.. If you have the error, we can try to see what was going on.

**Comment by rawxfish** [comment]
Gonna close for now, can raise a separate issue if the silk/`DEBUG` thing pops up again
